---
name: 'Perl (integration)'

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  perl-prove-with-tap:
    runs-on: ubuntu-latest
    name: "Prove (RAW TAP)"
    container:
      image: perldocker/perl-tester:5.26
    steps:
      - uses: actions/checkout@v4
      - run: cpanm --installdeps . --with-feature ci
      - run: PERL5LIB=$PWD/lib:$PERL5LIB prove --formatter TAP::Formatter::GitHubActions --merge

  perl-prove-with-tap-yaml:
    runs-on: ubuntu-latest
    name: "Prove (YAMLEnhancedTAP)"
    container:
      image: perldocker/perl-tester:5.26
    steps:
      - uses: actions/checkout@v4
      - run: cpanm --installdeps . --with-feature ci
      - run: PERL5LIB=$PWD/lib:$PERL5LIB T2_FORMATTER=YAMLEnhancedTAP prove --formatter TAP::Formatter::GitHubActions --merge
